/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootSpaRouteImport } from './routes/__root.spa'
import { Route as SystemHealthRouteImport } from './routes/system-health'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RollbackPointsRouteImport } from './routes/rollback-points'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const _rootSpaRoute = _rootSpaRouteImport.update({
  id: '/__root/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemHealthRoute = SystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RollbackPointsRoute = RollbackPointsRouteImport.update({
  id: '/rollback-points',
  path: '/rollback-points',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/register': typeof RegisterRoute
  '/rollback-points': typeof RollbackPointsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/spa': typeof _rootSpaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/register': typeof RegisterRoute
  '/rollback-points': typeof RollbackPointsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/spa': typeof _rootSpaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/register': typeof RegisterRoute
  '/rollback-points': typeof RollbackPointsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/__root/spa': typeof _rootSpaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/plugins'
    | '/register'
    | '/rollback-points'
    | '/settings'
    | '/system-health'
    | '/spa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/plugins'
    | '/register'
    | '/rollback-points'
    | '/settings'
    | '/system-health'
    | '/spa'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/plugins'
    | '/register'
    | '/rollback-points'
    | '/settings'
    | '/system-health'
    | '/__root/spa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PluginsRoute: typeof PluginsRoute
  RegisterRoute: typeof RegisterRoute
  RollbackPointsRoute: typeof RollbackPointsRoute
  SettingsRoute: typeof SettingsRoute
  SystemHealthRoute: typeof SystemHealthRoute
  _rootSpaRoute: typeof _rootSpaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/spa': {
      id: '/__root/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof _rootSpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-health': {
      id: '/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rollback-points': {
      id: '/rollback-points'
      path: '/rollback-points'
      fullPath: '/rollback-points'
      preLoaderRoute: typeof RollbackPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PluginsRoute: PluginsRoute,
  RegisterRoute: RegisterRoute,
  RollbackPointsRoute: RollbackPointsRoute,
  SettingsRoute: SettingsRoute,
  SystemHealthRoute: SystemHealthRoute,
  _rootSpaRoute: _rootSpaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
